### ISSUE TITLE
change call_user_func* with self invoked function

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-servicemanager#10]
- [x] Is this related to quality assurance?
As we already require php ^7.1 in develop branch

---

Originally posted by @samsonasik at https://github.com/zendframework/zend-servicemanager/pull/265

**Comment by weierophinney** [comment]
Scheduling for 4.0, as we support PHP 5.6 still in the 3.X series.

---

Originally posted by @weierophinney at https://github.com/zendframework/zend-servicemanager/pull/265#issuecomment-448013212

**Comment by samsonasik** [comment]
closed in favor of #37
