### ISSUE TITLE
syntax error unexpected '?' expecting function error PHP 7.4.23

### ISSUE THREAD

**Issue by desaiuttam** [laminas/laminas-servicemanager#108]
### Bug Report

Magento 2.4.3 Version
On Composer Install we require the laminas-servicemanager library.
The library has been Installed.

|    Q        |   A
|------------ | ------
| Version(s)  | 3.10.0

#### Summary

facing critical log as [2021-09-29 09:46:24] main.CRITICAL: ParseError: syntax error, unexpected '?', expecting function (T_FUNCTION) or const (T_CONST) in /home/production/vendor/laminas/laminas-servicemanager/src/ServiceManager.php:115

#### Current behavior

Critical Log after Update the library

#### How to reproduce
Framework: Magento
PHP: 7.4.23

Add Product to the cart
Move to the checkout page
Show the system.log there's error log reported as in describing

#### Expected behavior

If PHP 7.4 supports the library then no need for such an error because the environment is already working with PHP 7.4.23

**Comment by samsonasik** [comment]
already answered at https://github.com/laminas/laminas-servicemanager/pull/106#issuecomment-930123672 for different multiple php version installed. Please check php version that access it.
