### ISSUE TITLE
Package container-interop/container-interop is abandoned

### ISSUE THREAD

**Issue by spbentz** [laminas/laminas-servicemanager#109]
### BC Break Report

|    Q            |   A
|------------ | ------
| Version      |  3.10.0

#### Summary

Composer install returns:
"Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead."

**Comment by Ocramius** [comment]
Duplicate of https://github.com/laminas/laminas-servicemanager/pull/96
