### ISSUE TITLE
Use null coalescing operator

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-servicemanager#11]
---

Originally posted by @snapshotpl at https://github.com/zendframework/zend-servicemanager/pull/264

**Comment by weierophinney** [comment]
Scheduled for 4.0, as we still support PHP 5.6 in the version 3 releases.

---

Originally posted by @weierophinney at https://github.com/zendframework/zend-servicemanager/pull/264#issuecomment-448013032

**Comment by GeeH** [comment]
I'm closing this issue but wanted to call out @snapshotpl for the original fix. We know target PHP 7.3 so I'm going to open an issue to improve the code generally with these kind of fixes. Thank you for the contribution!
