### ISSUE TITLE
remove redundant isset(s)

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-servicemanager#12]
when we are also testing with `! empty()` I believe we can skip `isset()` checks, as the execution speed is nearly the same (but it will double for positive isset)

---

Originally posted by @pine3ree at https://github.com/zendframework/zend-servicemanager/pull/262

**Comment by weierophinney** [comment]
@pine3ree as this is an improvement, please target `develop`

---

Originally posted by @Ocramius at https://github.com/zendframework/zend-servicemanager/pull/262#issuecomment-370280536

**Comment by weierophinney** [comment]
@pine3ree please attempt a rebase - don't merge upstream into your dev branches :)

---

Originally posted by @Ocramius at https://github.com/zendframework/zend-servicemanager/pull/262#issuecomment-370363309

**Comment by weierophinney** [comment]
@pine3ree ah, that's alright. If you are not familiar with the rebase process, I'll just do it on merge :-)

---

Originally posted by @Ocramius at https://github.com/zendframework/zend-servicemanager/pull/262#issuecomment-370419760

**Comment by weierophinney** [comment]
ok, thank You @Ocramius ! kind regards! 

---

Originally posted by @pine3ree at https://github.com/zendframework/zend-servicemanager/pull/262#issuecomment-370420126

**Comment by weierophinney** [comment]
@pine3ree just in case you've other conflicted branch in other/next Pull Request, I made blog post about rebase conflicted branch https://samsonasik.wordpress.com/2015/09/16/practical-git-4-rebasing-conflicted-task-branch-against-primary-branch/

---

Originally posted by @samsonasik at https://github.com/zendframework/zend-servicemanager/pull/262#issuecomment-370637436

**Comment by weierophinney** [comment]
@samsonasik 
Thank You! that's very kind of You, sir! Regards!

---

Originally posted by @pine3ree at https://github.com/zendframework/zend-servicemanager/pull/262#issuecomment-370648122

**Comment by GeeH** [comment]
I'm going to close as this just doesn't wash it's face for a move to the new repo at the moment -- massive thank you to @pine3ree for the original contribution and please feel free to re-create this PR on this new repo if you wish.
