### ISSUE TITLE
Plugin manager does not allow callable as extended template parameter

### ISSUE THREAD

**Issue by gsteel** [laminas/laminas-servicemanager#139]
https://github.com/laminas/laminas-servicemanager/blob/05ac4b1fb1fe9333313eeafced9b6c7946589487/src/AbstractPluginManager.php#L35

The `of object` part here causes psalm error `InvalidTemplateParam` when extending the Plugin Manager with `@extends AbstractPluginManager<MyType>` where MyType includes `callable` - I didn't expect that :(

Removing `callable` fixes the error, but it's not valid for plugin managers that do return callables…

**Comment by boesing** [comment]
What plugin managers do return callables? 

Plugin managers are designed to only return objects. Thats why the `get` and `build` methods do use that `validate` method. 

Never seen any plugin manager within laminas which do return callables.

**Comment by gsteel** [comment]
View Helper Plugin Manager…

TBH, this is just lack of psalm understanding on my part. I can just return/accept `MyType|callable` in method annotations - it's just nice not to have to do that!!

**Comment by boesing** [comment]
Uff - was not aware that we have so much weird stuff in laminas 🙄

I actually have no time to wrap my head around this but if you want to bounce some ideas, let me know 👌🏻

**Comment by gsteel** [comment]
Thanks @boesing - Having a crack at Validator rn, view is just getting plain ugly :|
