### ISSUE TITLE
Add php 7.1 type hints

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-servicemanager#14]
---

Originally posted by @snapshotpl at https://github.com/zendframework/zend-servicemanager/pull/247

**Comment by weierophinney** [comment]
@snapshotpl this needs a rebase, sorry :-\

---

Originally posted by @Ocramius at https://github.com/zendframework/zend-servicemanager/pull/247#issuecomment-366471301

**Comment by weierophinney** [comment]
@Ocramius done!

---

Originally posted by @snapshotpl at https://github.com/zendframework/zend-servicemanager/pull/247#issuecomment-374408641

**Comment by GeeH** [comment]
I'm going to close this, part of my attention in working on this component is to add type hints and other general cleanup in one fell swoop. Thank you so much to @snapshotpl for this effort in the first place.
