### ISSUE TITLE
Expected ConfigAbstractFactory configuration per service manager

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-servicemanager#15]
I find the new Config Abstract Factory very handy. That saves a lot of typing. So thanks for that :clap:.

One thing that keeps bothering me however is that there seems to be only a single configuration array that determinates how services in all service manager are to be instantiated. You can mix plain services, controllers and view helpers! 

IMO that:

* Introduces some possible problems if service names are identical.
* Disallows one to properly split the configuration per service manager. When you have a lot of services it really helps to categorize them.

Another way of tackling this would be to add the config key directly as one of the components of the service manager config. But there are obviously other options.

```php
return [
    'factories => [],
    \Zend\ServiceManager\AbstractFactory\ConfigAbstractFactory::class => []
];
```

I am curious what other people think; or how they tackle this problem?

---

Originally posted by @roelvanduijnhoven at https://github.com/zendframework/zend-servicemanager/issues/212

**Comment by GeeH** [comment]
I'm closing this, it was a question rather than issue from over 3 years ago, I hope the OP found the resolution they needed!

**Comment by roelvanduijnhoven** [comment]
@GeeH OP is satisfied ;) and dit not use `ConfigAbstractFactory` in a long time:  `ReflectionBasedAbstractFactory` FTW!
