### ISSUE TITLE
Check that aliases work for every ServiceManager feature

### ISSUE THREAD

**Issue by Slamdunk** [laminas/laminas-servicemanager#158]
See https://github.com/laminas/laminas-form/pull/193#discussion_r995622387

A test shold be added to ensure that Factories, Abstract Factories, Delegators, Initializers, Services and so on work well with alias and aliased references when an alias is in place

**Comment by boesing** [comment]
Related to my RFC in #168 
Should we close here instead or should me make this one an RFC?

IMHO not a bug but a feature request tho.

**Comment by Slamdunk** [comment]
I'm not 100% sure they are the same topic: I'll let you decide though as it seems you have a much deeper knowledge and experience than me here

**Comment by boesing** [comment]
When I understand this issue correct, you want to ensure that delegator factories are called for aliases as well. 
Depending on how upstream configures/replaces SM configuration, this might not always work but at least we could add aliases delegator factories to the chain. 
Everything else, i.e. factories (which makes no sense in combination with aliases) and initializers do work (as they are triggered for all created services, no matter if aliased or not). 

Especially the issue you mentioned initially was one of the reason I've created the RFC as v4 is not that far away anymore.
