### ISSUE TITLE
Regression in type inference of `@psalm-type ServiceManagerConfiguration` on `ServiceManager`?

### ISSUE THREAD

**Issue by Ocramius** [laminas/laminas-servicemanager#165]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 3.20.0

#### Summary

When upgrading from `3.19.0` to `3.20.0`, the some type information got lost.

This is mostly visible in https://github.com/laminas/laminas-hydrator/pull/100 and similar patches, where errors like this one occur:

```
Error: src/HydratorPluginManagerFactory.php:48:64: ArgumentTypeCoercion: Argument 2 of Laminas\Hydrator\HydratorPluginManager::__construct expects array{abstract_factories?: array<array-key, Laminas\ServiceManager\Factory\AbstractFactoryInterface|class-string<Laminas\ServiceManager\Factory\AbstractFactoryInterface>>, aliases?: array<string, string>, delegators?: array<string, array<array-key, Laminas\ServiceManager\Factory\DelegatorFactoryInterface|callable(Psr\Container\ContainerInterface, string, callable():object, array<array-key, mixed>|null):object|class-string<Laminas\ServiceManager\Factory\DelegatorFactoryInterface>>>, factories?: array<string, Laminas\ServiceManager\Factory\FactoryInterface|callable(Psr\Container\ContainerInterface, null|string, array<array-key, mixed>|null):object|class-string<Laminas\ServiceManager\Factory\FactoryInterface>>, initializers?: array<array-key, Laminas\ServiceManager\Initializer\InitializerInterface|callable(Psr\Container\ContainerInterface, object):void|class-string<Laminas\ServiceManager\Initializer\InitializerInterface>>, invokables?: array<string, string>, lazy_services?: array{class_map?: array<string, class-string>, proxies_namespace?: non-empty-string, proxies_target_dir?: non-empty-string, write_proxy_files?: bool}, services?: array<string, array<array-key, mixed>|object>, shared?: array<string, bool>, shared_by_default?: bool, ...<array-key, mixed>}, but parent type array<array-key, mixed> provided (see https://psalm.dev/193)
```

Seems like this declaration is mis-interpreted due to the final `...` :thinking: 

https://github.com/laminas/laminas-servicemanager/blob/e5cfad71185ed47aa0b41db81d4ea6a84ca5cb0e/src/ServiceManager.php#L62-L74

Possibly also a psalm bug?

**Comment by gsteel** [comment]
I think this is because psalm 4.30 (present in the lockfile) does not understand `...` - Upgrading to psalm 5 in the these libs should just solve everything like https://github.com/mezzio/mezzio-laminasviewrenderer/pull/33

**Comment by Ocramius** [comment]
Hmm, true that :thinking: 

Perhaps really a question of upgrading `vimeo/psalm` :+1:

**Comment by boesing** [comment]
I've modified the types a little bit in #179 as I found some issues there. Maybe that also fixes this issue?
Should we close here or do you want us to dive deeper into this?

**Comment by boesing** [comment]
Closing here as it should be handled by #179
