### ISSUE TITLE
Release blocker 3.22.0

### ISSUE THREAD

**Issue by boesing** [laminas/laminas-servicemanager#199]
This Ticket is meant to block branches which are polluted by renovate due to auto-merge.

As @Xerkus mentioned in Slack, renovate somehow merged v4 to v3 within https://github.com/laminas/laminas-servicemanager/pull/185 in order of a lock-file maintenance.

To avoid that someone accidentally creates a release here, I'll block 3.22.0 and 3.21.1 with this issue(s).

**Comment by Xerkus** [comment]
Changes reversed by force push to dev branch.
