### ISSUE TITLE
Created tool to inject factory maps into configuration

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-servicemanager#21]
This patch adds a new tool, `create-factory-map`, which will map a given class to a given factory in the specified configuration file, under the provided configuration key (defaulting to `service_manager`).

```
Usage:

  ./vendor/zendframework/zend-servicemanager/bin/create-factory-map [-h|--help|help] <configFile> <className> <factoryName> [<key>]

Arguments:

  -h|--help|help    This usage message
  <configFile>      Path to an config file in which to map the factory.
                    If the file does not exist, it will be created. If
                    it does exist, it must return an array.
  <className>       Name of the class to map to a factory.
  <factoryName>     Name of the factory class to use with <className>.
  [<key>]           (Optional) The top-level configuration key under which
                    the factory map should appear; defaults to
                    "service_manager".
```

As part of this work, I moved the methods for dumping configuration files into a trait; this trait is now composed by both the `ConfigDumper` and `FactoryMapperCommand`.

---

Originally posted by @weierophinney at https://github.com/zendframework/zend-servicemanager/pull/161

**Comment by weierophinney** [comment]
@GeeH I think this completes the pieces we need for the 3.2 release; can you review?


---

Originally posted by @weierophinney at https://github.com/zendframework/zend-servicemanager/pull/161#issuecomment-248917197

**Comment by weierophinney** [comment]
ping @GeeH would be great to have this can you review? just a reminder in case you forgot :)

---

Originally posted by @svycka at https://github.com/zendframework/zend-servicemanager/pull/161#issuecomment-265113871

**Comment by weierophinney** [comment]
I spoke to @weierophinney in person which is naughty and I should have commented on here. @weierophinney I suggest we release 3.2 as it is and make further improvements in this area for 3.3.


---

Originally posted by @GeeH at https://github.com/zendframework/zend-servicemanager/pull/161#issuecomment-265116243

**Comment by weierophinney** [comment]
Moved target milestone to `3.4.0`

---

Originally posted by @Ocramius at https://github.com/zendframework/zend-servicemanager/pull/161#issuecomment-356202202

**Comment by GeeH** [comment]
@weierophinney I forget what the hell we did here; do we want to release this as part of the 3.5 release I'm working towards?

**Comment by boesing** [comment]
Closing here as the PR was never re-opened and I do not want to dive too deep into this as of now. If this is still a feature we want to ship at some point, feel free to re-open the PR on top of #176
