### ISSUE TITLE
Write new tutorial documentation for moving from ConfigAbstractFactory

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-servicemanager#22]
It might be a good idea to demonstrate in the documentation a migration path from this abstract factory to an explicit factory. One of the frequent comments I've seen from folks about the deprecation of ServiceLocatorAware is that developers are unaware of how to write factories. Including some explicit steps here will help them when they have the question of, "I need to do something that falls outside the scope of this abstract factory, but I don't know how."

---

Originally posted by @GeeH at https://github.com/zendframework/zend-servicemanager/issues/149

**Comment by weierophinney** [comment]
@GeeH Question: you mentioned at one point in development of #146 that you might write a tool that would create a factory/factories from `ConfigAbstractFactory` configuration. Do you still plan that? If so, I think we could defer this until that tool is available.

Also, wondering, because if you are planning that, I'm curious if you think we should delay the 3.2.0 release until it's ready...


---

Originally posted by @weierophinney at https://github.com/zendframework/zend-servicemanager/issues/149#issuecomment-244201769

**Comment by weierophinney** [comment]
Is the [current doc's page](https://docs.zendframework.com/zend-servicemanager/cookbook/factories-vs-abstract-factories/) enough to explain the differences between Abstract Factories and Explicit Factories mentioned here and in #148 ?
I've seen it currently largely describes Comparisons, Convenience, etc.

If it is enough, I think this issue was already resolved by #150 , so it should be closed.

---

Originally posted by @renanliberato at https://github.com/zendframework/zend-servicemanager/issues/149#issuecomment-349683959

**Comment by boesing** [comment]
I wonder if this is somehow fixed by #180 - even tho it does not create a factory based on `ConfigAbstractFactory` but on `ReflectionBasedAbstractFactory`.

Anyways, closing this as it is open since 2016 and there was no progress until 2023. Even tho we did not reached the 10 year mark here, I guess we can close this without stepping on anyones toes?
