### ISSUE TITLE
psr/container version issue in drupal 10.2.2 

### ISSUE THREAD

**Issue by mktomanikandan** [laminas/laminas-servicemanager#220]
Root composer.json requires laminas/laminas-servicemanager 3.22.1 -> satisfiable by laminas/laminas-servicemanager[3.22.1].
    - laminas/laminas-servicemanager 3.22.1 requires psr/container ^1.0 -> found psr/container[1.0.0, 1.1.0, 1.1.1, 1.1.2, 1.1.x-dev, 1.x-dev] but it conflicts with your root composer.json require (~2.0.2).
  Problem 2
    - laminas/laminas-servicemanager 3.22.1 requires psr/container ^1.0 -> found psr/container[1.0.0, 1.1.0, 1.1.1, 1.1.2, 1.1.x-dev, 1.x-dev] but it conflicts with your root composer.json require (~2.0.2).
    - laminas/laminas-text[2.10.0, 2.10.x-dev] require laminas/laminas-servicemanager ^3.19.0 -> satisfiable by laminas/laminas-servicemanager[3.22.1].
    - Root composer.json requires laminas/laminas-text ~2.10.0 -> satisfiable by laminas/laminas-text[2.10.0, 2.10.x-dev].

### BC Break Report

|    Q        |   A
|------------ | ------
| Version     | x.y.z

**Comment by gsteel** [comment]
The 3.x series of `laminas-servicemanager` does not support `psr/container@2.0`. Version 4.0 is in the works and will support it. In the mean time, you'll need to adjust your constraints to `psr/container: ^1.0 || ^2.0`
