### ISSUE TITLE
Programmatically set shared false on a service after it has been called once when shared was true return the previously created service.

### ISSUE THREAD

**Issue by e-belair** [laminas/laminas-servicemanager#229]
### Bug Report

Programmatically set shared false on a service after it has been called once when shared was true return the previously created service.

|    Q        |   A
|------------ | ------
| Version(s)  | latest

#### Summary
I know that is not often we need to share or not a service during the execution. I had to do that while testing a service with different configurations.

So I discovered [here](https://github.com/laminas/laminas-servicemanager/blob/db2250cb5909ca07f517d9d9064e667aa40e4d6b/src/ServiceManager.php#L200) that the sm first check if the service is cached before checking if it's shared. This works fine if we don't programmatically change the shared state of the service, but it can have a bad behavior if we do.

#### How to reproduce
```php
// Assume that MyService::class is shared by default
$service1 = $sm->get(MyService::class)
$sm->setShared(MyService::class, false)
$service2 = $sm->get(MyService::class)
// $service1 and $service2 are the same instance
```
#### Expected behavior

$service1 and $service2 should not be the same instance has we set shared to false

**Comment by Ocramius** [comment]
I'd say that `$sm` mutation after **use** is a bad idea overall.

I'd be more inclined to "freeze" the service manager after configuration (which would require a new major version anyway), rather than allowing this sort of edge case.

**Comment by Ocramius** [comment]
I'd like to close this as "Won't fix", but the correct resolution would be to have a test case that says "this is expected / normal"

**Comment by e-belair** [comment]
I suspected the answer but thought reporting the bug was important.
However, I could resolve the problem by unsetting the service to force its creation.
```php
$sm->setService(MyService::class, null)
$sm->get(MyService::class)
```

**Comment by Ocramius** [comment]
Thanks! 

I'll close here: will use the issue as reference, but I think we shouldn't invest more time into it (for now)
