### ISSUE TITLE
ViewHelperPlugin manager configure problem

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-servicemanager#25]
ViewHelperManager is special type of ServiceManager. There is problem with flushing instances with configure (SM 3.0). It is needed for still alive applications e.g on ReactPHP

``` php
['HelperName' => null] + $this->services
```

does not work, because there is plugin validation.

---

Originally posted by @visitek at https://github.com/zendframework/zend-servicemanager/issues/107

**Comment by weierophinney** [comment]
The issue is unclear to me, and requires a test case in order to be verified


---

Originally posted by @Ocramius at https://github.com/zendframework/zend-servicemanager/issues/107#issuecomment-222981834

**Comment by GeeH** [comment]
It is over 4 years since this was raised and has had no communication from author in over 4 years. I'm closing this.
