### ISSUE TITLE
Change resolveParameter method to protected

### ISSUE THREAD

**Issue by adambalint-srg** [laminas/laminas-servicemanager#29]
### Feature Request

The method: https://github.com/laminas/laminas-servicemanager/blob/d7c44852928ff8aa774db45defd45c631dc7856a/src/AbstractFactory/ReflectionBasedAbstractFactory.php#L207
Change this method to protected would be useful for other custom factories.

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

What do you think? Are there any reason, why this method (ReflectionBasedAbstractFactory's resolveParameter) is private? It is very useful, and it would be very good if I can use it in other factories without reimplementing the whole function.
If not, I can create a pull request

**Comment by GeeH** [comment]
I think moving this to protected is sensible if people would like to extend the `ReflectionBasedAbstractFactory` and implement slightly different versions. Any thoughts? I'm guessing @Ocramius will have *opinions* on this.

**Comment by Ocramius** [comment]
I don't think extension is a good approach here: the factory can be copied over (with tests) and re-implemented differently.

`protected` is mostly to be used for `abstract` types with extremely strict invariants (only)

**Comment by Ocramius** [comment]
Closing here: this is a clear scenario whete copying code is indeed preferable (please copy also the tests)
