### ISSUE TITLE
Zend\ServiceManager\AbstractFactory\ConfigAbstractFactory::class key in config is ignored after migration to Laminas

### ISSUE THREAD

**Issue by chris1312** [laminas/laminas-servicemanager#30]
### BC Break Report

|    Q        |   A
|------------ | ------
| Version     | latest

#### Summary

My project is using external modules that are placed under vendor directory. Those external modules contains services that are defined under Zend\ServiceManager\AbstractFactory\ConfigAbstractFactory::class.

After project is migrated to Laminas, service manager is ignoring the services defined under Zend\ServiceManager\AbstractFactory\ConfigAbstractFactory::class.

**Comment by chris1312** [comment]
@weierophinney Is this indented behavior?

**Comment by Xerkus** [comment]
@chris1312 Can you please verify that you have `Laminas\ZendFrameworkBridge` module enabled?

**Comment by chris1312** [comment]
It was not. 
Enabling it solved the issue. Thanks for the help @Xerkus !
