### ISSUE TITLE
Added PHP 7.3 support

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-servicemanager#6]
Updated Travis CI configuration to run all tests on PHP 7.3 with lowest/locked/latest dependencies

---

Originally posted by @michalbundyra at https://github.com/zendframework/zend-servicemanager/pull/273

**Comment by weierophinney** [comment]
@Ocramius, updated now. Not sure about the milestone 3.4.0 as develop now is 4.0:

```
 "dev-develop": "4.0-dev"
```

Maybe I should change the target of that PR?

---

Originally posted by @michalbundyra at https://github.com/zendframework/zend-servicemanager/pull/273#issuecomment-429818255

**Comment by weierophinney** [comment]
@webimpress I was working on 4.0 on `develop`, but it will likely happen in +1 year anyway, since PHP 7.4 will have the interesting stuff, while 7.3 is kinda dull :)

---

Originally posted by @Ocramius at https://github.com/zendframework/zend-servicemanager/pull/273#issuecomment-429819690

**Comment by weierophinney** [comment]
@Xerkus I forgot about this PR and just created new to `master`: #277 

---

Originally posted by @michalbundyra at https://github.com/zendframework/zend-servicemanager/pull/273#issuecomment-448906471

**Comment by weierophinney** [comment]
I think suggested `ocramius/proxy-manager` should be bumped to `^2.2.0`, along with dev dependency, and conflict changed to specific version of `"zendframework/zend-code": "3.3.0"` to reduce unintended impact

---

Originally posted by @Xerkus at https://github.com/zendframework/zend-servicemanager/pull/273#issuecomment-488390794

**Comment by Ocramius** [comment]
Handled in #42
