### ISSUE TITLE
Overwriting an invokable with a factory does not work

### ISSUE THREAD

**Issue by alexz707** [laminas/laminas-servicemanager#68]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 3.5.1

#### Summary

The config get's merged not as expected.
I have a vendor's config in Module.php like this:
```PHP
invokables' => [
    'lmcuser_register_form_hydrator' => \Laminas\Hydrator\ClassMethodsHydrator::class,
]
```
I want to overide this one with a factory in my module.config.php:

```PHP
    'service_manager' => [
        'factories' => [
            'lmcuser_register_form_hydrator' => DoctrineHydratorfactory::class,
        ],
```
#### Current behavior

If I try to get the 'lmcuser_register_form_hydrator' from ServiceManager I get the ClassMethodsHydrator::class.

#### How to reproduce

Just overwrite a invokable (which gets aliased) with a factory and try to get it with dem sm.

#### Expected behavior
I would expect to get an Object from the DoctrineHydratorfactory::class which would give me in my case a DoctrineObject.

I think it has to do with the way invokables get aliased and then merged with the other config.
Maybe the array_merge arguments just have to be switched?

Servicemanager.php on line 325
```PHP
            if (! empty($aliases)) {
                $config['aliases'] = (isset($config['aliases']))
                    ? array_merge($config['aliases'], $aliases)
                    : $aliases;
            }
```

**Comment by syberon** [comment]
Today i found the same bug in version 3.6.1 - all overwritten invokables are ignored.

The reason is in ServiceManager.php on line 376:
```
if (! empty($config['aliases'])) {
    $this->aliases = $config['aliases'] + $this->aliases;
    $this->mapAliasesToTargets();
} elseif (! $this->configured && ! empty($this->aliases)) {
    $this->mapAliasesToTargets();
}
```

This assignment overwrites all custom declared invokables by default values. To fix this bug this line should be:
`$this->aliases = $this->aliases + $config['aliases'];`

**Comment by Ocramius** [comment]
@syberon can you produce a failing test case, please?
Should be easy to fix once that is available.

**Comment by driehle** [comment]
I am having the same issue, related with the `neilime/twbs-helper-module` library. The issue appears with service manager 3.6.0 and 3.6.1, but not with 3.5.1. So for now I downgraded with `composer require laminas/laminas-servicemanager:"~3.5.0"`.

**Comment by driehle** [comment]
Not a 100% sure, but I might have found a suitable test case for @syberon's problem:

```php
    public function testConfigureCanOverrideAliasesWithFactories()
    {
        $firstFactory  = $this->getMockBuilder(FactoryInterface::class)
            ->getMock();
        $secondFactory = $this->getMockBuilder(FactoryInterface::class)
            ->getMock();
        $thirdFactory  = $this->getMockBuilder(FactoryInterface::class)
            ->getMock();

        $serviceManager = $this->createContainer([
            'invokables' => [
                'alias1' => DateTime::class,
            ],
            'factories' => [
                DateTimeZone::class => $firstFactory,
            ],
            'aliases' => [
                'alias2' => DateTimeZone::class,
            ],
        ]);

        $newServiceManager = $serviceManager->configure([
            'factories' => [
                'alias1' => $secondFactory,
                'alias2' => $thirdFactory,
            ],
        ]);

        $this->assertSame($serviceManager, $newServiceManager);

        $firstFactory->expects($this->never())->method('__invoke');
        $secondFactory->expects($this->once())->method('__invoke');
        $thirdFactory->expects($this->once())->method('__invoke');

        $newServiceManager->get('alias1');
        $newServiceManager->get('alias2');
    }
```

Once an alias is set, it is not overriden if a new factory is registered for the same string. A solution might be what I have done with [bd15fbb9](https://github.com/driehle/laminas-servicemanager/commit/bd15fbb93bf9d0e8ae83c365fa5921b581e7d7e7). However, I am not sure if this is actually related to 3.6.1, because I cannot get the same test to pass with service manager 3.5.x branch. Was 3.5.x already broken as well?

**Comment by driehle** [comment]
I had a deeper look at neilime/twbs-helper-module#128 and found that what actually happens is that config is merged from different sources and then `configure()` is called with something like this:

```
array:9 [?
  "abstract_factories" => []
  "aliases" => array:277 [?
    "formsubmit" => "Laminas\Form\View\Helper\FormSubmit"
    "form_submit" => "Laminas\Form\View\Helper\FormSubmit"
    "formSubmit" => "Laminas\Form\View\Helper\FormSubmit"
    "FormSubmit" => "Laminas\Form\View\Helper\FormSubmit"
    [...]
  ]
  "delegators" => []
  "factories" => array:63 [?
    "Laminas\Form\View\Helper\FormSubmit" => "Laminas\ServiceManager\Factory\InvokableFactory"
    [...]
  ]
  "initializers" => []
  "invokables" => array:69 [?
    [...]
    "formSubmit" => "TwbsHelper\Form\View\Helper\FormButton"
    "form_submit" => "TwbsHelper\Form\View\Helper\FormButton"
    "formsubmit" => "TwbsHelper\Form\View\Helper\FormButton"
  ]
  "lazy_services" => []
  "services" => []
  "shared" => []
]
```

So obviously this configuration is inconsistent by itself. According to `invokables` the Submit element should be used from TwbsHelper, however, according to `aliases` and `factories` the element should be used from laminas. 

With that it all comes down to which of these configurations takes precedence. And, indeed, it looks like that behaviour has changed. The following test passes for 3.5.1 (using PHP 7.4, running `composer update` and `composer test`) while it failes for 3.6.1 (same setting):

```php
    public function testConfigureInvokablesTakePrecedenceOverFactories()
    {
        $firstFactory  = $this->getMockBuilder(FactoryInterface::class)
            ->getMock();

        $serviceManager = $this->createContainer([
            'aliases' => [
                'custom_alias' => DateTime::class,
            ],
            'factories' => [
                DateTime::class => $firstFactory,
            ],
            'invokables' => [
                'custom_alias' => stdClass::class,
            ],
        ]);

        $firstFactory->expects($this->never())->method('__invoke');

        $object = $serviceManager->get('custom_alias');
        $this->assertInstanceOf(stdClass::class, $object);
    }
```

See [d9e4f6a8](https://github.com/driehle/laminas-servicemanager/commit/d9e4f6a817a131821598123cf889595f04fdb7f0) for a potential fix.

**Comment by driehle** [comment]
@alexz707 With the release of 3.6.2 the BC break has been fixed. Nevertheless, if a vendor defines an invokable like this:

```
'invokables' => [
    'lmcuser_register_form_hydrator' => \Laminas\Hydrator\ClassMethodsHydrator::class,
]
```

You will have to keep in mind that the seminar manager internally rewrites this to the following:

```
'factories' => [
    \Laminas\Hydrator\ClassMethodsHydrator::class => \Laminas\ServiceManager\Factory\InvokableFactory::class,
]
'aliases' => [
    'lmcuser_register_form_hydrator' => \Laminas\Hydrator\ClassMethodsHydrator::class,
]
```

Therefore, for overriding this with your own factory, you will have to either override the invokable with an invokable (which likely won't help you, since your own class seems to need a factory) or you will have to override the factory or the alias as defined above.

**Comment by boesing** [comment]
@alexz707 did servicemanager v3.6.2 fixed your problem? If so, please let us know so we can mark this as fixed.

**Comment by syberon** [comment]
In my case v3.6.2 successfully fixed the problem.

**Comment by boesing** [comment]
Closing this as there was no update from the author recently and it seems that it has been fixed for others.
If you still experience issues, please let us know by commenting this issue.
