### ISSUE TITLE
phpstan fixes

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-servicemanager#7]
This PR fixes some issues with phpdoc and types. Used phpstan to static analyse the code.

Added `phpstan` in CI build.

---

Originally posted by @thomasvargiu at https://github.com/zendframework/zend-servicemanager/pull/272

**Comment by weierophinney** [comment]
I've added phpstan in CI build and fixed some wrong uses of `array_key_exists` with `ArrayObject`.

---

Originally posted by @thomasvargiu at https://github.com/zendframework/zend-servicemanager/pull/272#issuecomment-431324970

**Comment by weierophinney** [comment]
@thomasvargiu I've just noticed that this targets `master`: can you change it to `develop`? Since it's an improvement, it needs to target the next minor or major.

---

Originally posted by @Ocramius at https://github.com/zendframework/zend-servicemanager/pull/272#issuecomment-431342559

**Comment by weierophinney** [comment]
Please rebase, don't merge :)

---

Originally posted by @Ocramius at https://github.com/zendframework/zend-servicemanager/pull/272#issuecomment-431349333

**Comment by weierophinney** [comment]
My fault, I'm still working on it

---

Originally posted by @thomasvargiu at https://github.com/zendframework/zend-servicemanager/pull/272#issuecomment-431349622

**Comment by weierophinney** [comment]
@Ocramius 
I have just one issue that I want to fix:

```
------ ----------------------------------------------------------------------------------------------------------------------------
  Line   src/AbstractPluginManager.php
 ------ ----------------------------------------------------------------------------------------------------------------------------
  130    Parameter #1 $instance of method Zend\ServiceManager\AbstractPluginManager::validate() expects object, array|object given.
 ------ ----------------------------------------------------------------------------------------------------------------------------
```

I think we should change PHPDoc of `$instance` parameter in `Zend\ServiceManager\PluginManagerInterface::validate()` from `object` to `mixed` because we know that `services` config key can contain anything.

But I'm not sure about this change. We can also ignore the error at the moment.

What do you think about it?

---

Originally posted by @thomasvargiu at https://github.com/zendframework/zend-servicemanager/pull/272#issuecomment-431362694

**Comment by weierophinney** [comment]
> I've noted that phpstan should only be added for Travis jobs that require it, not as a general dev dependency.

Done.

> Additionally, I'll note that a large number of the changes presented here are present in other pull requests; you'll likely need to rebase and run again once those are in place.

It's not a problem, when I open it I though that it could be useful before to introduce strict type hints. We can merge other PRs and then rebase it.


---

Originally posted by @thomasvargiu at https://github.com/zendframework/zend-servicemanager/pull/272#issuecomment-448161661

**Comment by weierophinney** [comment]
Rescheduling to 4.0.0 since it targets develop in turn targeting 4.0

---

Originally posted by @Xerkus at https://github.com/zendframework/zend-servicemanager/pull/272#issuecomment-448929352

**Comment by weierophinney** [comment]
@weierophinney I rebased it, updated phpstan, done some other fixes.

I also allowed `array` in the PluginManager `validate()` method.

---

Originally posted by @thomasvargiu at https://github.com/zendframework/zend-servicemanager/pull/272#issuecomment-474592342

**Comment by GeeH** [comment]
@laminas/technical-steering-committee  is PHPStan fixes valid now or are we going all in with Psalm in the future? Do we see value in pull these changes across please?

**Comment by GeeH** [comment]
Ping @mwop @Ocramius

**Comment by samsonasik** [comment]
Based on this https://github.com/laminas/technical-steering-committee/blob/c896c3af8fcbe0b3df82751e8bfeb54b536cc2e9/meetings/minutes/2020-08-03-TSC-Minutes.md#vote-on-static-analysis-tooling , we are going to use psalm. 

I am closing this.
