### ISSUE TITLE
Running composer cs-check is broken on PHP 8.0

### ISSUE THREAD

**Issue by jensdenies** [laminas/laminas-servicemanager#73]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 3.6.1

#### Summary

When running the composer command `composer cs-check`, you'll be greeted with the following error message:

`Fatal error: Array and string offset access syntax with curly braces is no longer supported in Laminas-servicemanager/vendor/squizlabs/php_codesniffer/CodeSniffer/CLI.php on line 453`

**Comment by snapshotpl** [comment]
That's why `cs-check` runs on PHP 7.3 in travis. It's problem with missing php8 support in CodeSniffer

**Comment by boesing** [comment]
Yup, we do not run codestandard on multiple versions. Just execute codestandard on the same PHP version as its been done in the `.travis.yml` configuration.
