### ISSUE TITLE
Incorrect PHP version constraint

### ISSUE THREAD

**Issue by hschletz** [laminas/laminas-servicemanager#84]
According to documentation, 3.6 and later require PHP 7.4 or later, but the package has an inadequate version constraint:

    "php": "^7.3 || ~8.0.0",

This makes the package installable with PHP 7.3 when it shouldn't. The constraint should be updated.

**Comment by boesing** [comment]
Could you provide a link to the mentioned documentation? 
The package is fully tested on PHP 7.3 and thus indeed functional aswell. 
So the constraint is absolutely correct as you can see in the CI pipeline.

Do you have any problems on 7.3?

**Comment by hschletz** [comment]
Mentioned in the release notes: https://github.com/laminas/laminas-servicemanager/releases/tag/3.6.0
See #50

**Comment by Ocramius** [comment]
The notes state:

> re-adds PHP 7.3 support.

**Comment by hschletz** [comment]
Sorry, just noticed that. Mentioning both in the same release notes is a bit confusing...
